# region copyright
# Copyright 2023 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# endregion

- name: Make sure dirs exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  with_items:
    - /home/{{ ansible_user }}/Pictures
    - /home/{{ ansible_user }}/Desktop

- name: Upload OV Icon
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ansible_user }}/Pictures/{{ item }}"
    mode: 0644
  with_items:
    - ov-icon.png

- name: Download OV Launcher
  get_url:
    url: https://install.launcher.omniverse.nvidia.com/installers/omniverse-launcher-linux.AppImage
    dest: "/home/{{ ansible_user }}/Omniverse.AppImage"
    mode: 0755
  become_user: "{{ ansible_user }}"

- name: Create desktop icon
  copy:
    content: |
      [Desktop Entry]
      Name=Omniverse Launcher
      Comment=Omniverse Launcher
      Exec=/home/{{ ansible_user }}/Omniverse.AppImage
      Icon=/home/{{ ansible_user }}/Pictures/ov-icon.png
      Terminal=false
      Type=Application
      Categories=Utility;
    dest: /home/{{ ansible_user }}/Desktop/ovl.desktop
    mode: 0644

- name: Allow execution of OVL desktop icon
  shell: gio set /home/{{ ansible_user }}/Desktop/{{ item }} metadata::trusted true
  become_user: "{{ ansible_user }}"
  with_items:
    - ovl.desktop

- name: Set permissions for OVL desktop icon
  file:
    path: /home/{{ ansible_user }}/Desktop/{{ item }}
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - ovl.desktop
