name: Test Deployment to AWS

on:
  push:
    paths:
      - ".github/workflows/deploy-aws.yml"

jobs:
  deploy:
    runs-on: ghcr.io/nvidia-omniverse/isaacsim-automator/app-image:latest
    steps:
      - name: Test
        run: |
          echo "Hello World"
